//
//  STPhotoDetailsWorkerTests.swift
//  STPhotoDetails
//
//  Created by Dimitri Strauneanu on 25/07/2019.
//  Copyright (c) 2019 Streetography. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import STPhotoDetails
import XCTest
import STPhotoCore

class STPhotoDetailsWorkerTests: XCTestCase {
    var sut: STPhotoDetailsWorker!
    var delegateSpy: STPhotoDetailsWorkerDelegateSpy!
    
    // MARK: - Test lifecycle
    
    override func setUp() {
        super.setUp()
        self.setupSTPhotoDetailsWorker()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: - Test setup
    
    func setupSTPhotoDetailsWorker() {
        self.delegateSpy = STPhotoDetailsWorkerDelegateSpy()
        
        self.sut = STPhotoDetailsWorker(delegate: self.delegateSpy)
    }
    
    // MARK: - Tests
    
    func testFetchPhotoImage() {
        let spy = ImageLocalTaskSpy()
        self.sut.imageTask = spy
        self.sut.fetchPhotoImage(url: "https://streetography.com")
        XCTAssertTrue(spy.fetchImageCalled)
    }
    
    func testFetchPhotoImageShouldAskTheDelegateToSendImageForSuccessCase() {
        let spy = ImageLocalTaskSpy()
        spy.shouldFailFetchImage = false
        self.sut.imageTask = spy
        
        self.sut.fetchPhotoImage(url: "https://streetography.com")
        XCTAssertTrue(self.delegateSpy.successDidFetchPhotoImageCalled)
    }
    
    func testFetchPhotoImageShouldAskTheDelegateToSendErrorForFailureCase() {
        let spy = ImageLocalTaskSpy()
        spy.shouldFailFetchImage = true
        self.sut.imageTask = spy
        
        self.sut.fetchPhotoImage(url: "https://streetography.com")
        XCTAssertTrue(self.delegateSpy.failureDidFetchPhotoImageCalled)
    }
    
    func testFetchPhotoUserImage() {
        let spy = ImageLocalTaskSpy()
        self.sut.imageTask = spy
        self.sut.fetchPhotoUserImage(url: "https://streetography.com")
        XCTAssertTrue(spy.fetchImageCalled)
    }
    
    func testFetchPhotoUserImageShouldAskTheDelegateToSendImageForSuccessCase() {
        let spy = ImageLocalTaskSpy()
        spy.shouldFailFetchImage = false
        self.sut.imageTask = spy
        
        self.sut.fetchPhotoUserImage(url: "https://streetography.com")
        XCTAssertTrue(self.delegateSpy.successDidFetchPhotoUserImageCalled)
    }
    
    func testFetchPhotoUserImageShouldAskTheDelegateToSendErrorForFailureCase() {
        let spy = ImageLocalTaskSpy()
        spy.shouldFailFetchImage = true
        self.sut.imageTask = spy
        
        self.sut.fetchPhotoUserImage(url: "https://streetography.com")
        XCTAssertTrue(self.delegateSpy.failureDidFetchPhotoUserImageCalled)
    }
    
    func testFetchPhoto() {
        let spy = PhotoLocalTaskSpy()
        self.sut.photoTask = spy
        self.sut.fetchPhoto(photoId: "photoId")
        XCTAssertTrue(spy.fetchPhotoCalled)
    }
    
    func testFetchPhotoShouldAskTheDelegateToSendPhotoForSuccessCase() {
        let spy = PhotoLocalTaskSpy()
        spy.shouldFailFetchPhoto = false
        self.sut.photoTask = spy
        self.sut.fetchPhoto(photoId: "photoId")
        XCTAssertTrue(self.delegateSpy.successDidFetchPhotoCalled)
    }
    
    func testFetchPhotoShouldAskTheDelegateToSendErrorForFailureCase() {
        let spy = PhotoLocalTaskSpy()
        spy.shouldFailFetchPhoto = true
        self.sut.photoTask = spy
        self.sut.fetchPhoto(photoId: "photoId")
        XCTAssertTrue(self.delegateSpy.failureDidFetchPhotoCalled)
    }
    
    func testFetchPhotoCollection() {
        let spy = PhotoCollectionLocalTaskSpy()
        self.sut.photoCollectionTask = spy
        self.sut.fetchPhotoCollection(id: "collectionId")
        XCTAssertTrue(spy.fetchPhotoCollectionCalled)
    }
    
    func testFetchPhotoCollectionShouldAskTheDelegateToSendCollectionForSuccessCase() {
        let spy = PhotoCollectionLocalTaskSpy()
        spy.shouldFailFetchPhotoCollection = false
        self.sut.photoCollectionTask = spy
        self.sut.fetchPhotoCollection(id: "collectionId")
        XCTAssertTrue(self.delegateSpy.successDidFetchPhotoCollectionCalled)
    }
    
    func testFetchPhotoCollectionShouldAskTheDelegateToSendErrorForFailureCase() {
        let spy = PhotoCollectionLocalTaskSpy()
        spy.shouldFailFetchPhotoCollection = true
        self.sut.photoCollectionTask = spy
        self.sut.fetchPhotoCollection(id: "collectionId")
        XCTAssertTrue(self.delegateSpy.failureDidFetchPhotoCollectionCalled)
    }
    
    func testFetchPhotoLocationAddress() {
        let spy = LocationAddressLocalTaskSpy()
        self.sut.locationAddressTask = spy
        self.sut.fetchPhotoLocationAddress(location: STLocation(latitude: 46, longitude: 25))
        XCTAssertTrue(spy.fetchLocationAddressCalled)
    }
    
    func testFetchPhotoLocationAddressShouldAskTheDelegateToSendAddressForSuccessCase() {
        let spy = LocationAddressLocalTaskSpy()
        spy.shouldFailFetchLocationAddress = false
        self.sut.locationAddressTask = spy
        self.sut.fetchPhotoLocationAddress(location: STLocation(latitude: 46, longitude: 25))
        XCTAssertTrue(self.delegateSpy.successDidFetchLocationAddressCalled)
    }
    
    func testFetchPhotoLocationAddressShouldAskTheDelegateToSendErrorForFailureCase() {
        let spy = LocationAddressLocalTaskSpy()
        spy.shouldFailFetchLocationAddress = true
        self.sut.locationAddressTask = spy
        self.sut.fetchPhotoLocationAddress(location: STLocation(latitude: 46, longitude: 25))
        XCTAssertTrue(self.delegateSpy.failureDidFetchLocationAddressCalled)
    }
    
    func testFetchPhotoLocationEntities() {
        let spy = LocationEntitiesLocalTaskSpy()
        self.sut.locationEntitiesTask = spy
        self.sut.fetchPhotoLocationEntities(location: STLocation(latitude: 46, longitude: 25))
        XCTAssertTrue(spy.fetchPhotoEntitiesCalled)
    }
    
    func testFetchPhotoLocationEntitiesShouldAskTheDelegateToSendEntitiesForSuccessCase() {
        let spy = LocationEntitiesLocalTaskSpy()
        spy.shouldFailFetchPhotoEntities = false
        self.sut.locationEntitiesTask = spy
        self.sut.fetchPhotoLocationEntities(location: STLocation(latitude: 46, longitude: 25))
        XCTAssertTrue(self.delegateSpy.successDidFetchPhotoLocationEntitiesCalled)
    }
    
    func testFetchPhotoLocationEntitiesShouldAskTheDelegateToSendErrorForFailureCase() {
        let spy = LocationEntitiesLocalTaskSpy()
        spy.shouldFailFetchPhotoEntities = true
        self.sut.locationEntitiesTask = spy
        self.sut.fetchPhotoLocationEntities(location: STLocation(latitude: 46, longitude: 25))
        XCTAssertTrue(self.delegateSpy.failureDidFetchPhotoLocationEntitiesCalled)
    }
}
