//
//  STPhotoCommentsRouter.swift
//  STPhotoDetails
//
//  Created by Dimitri Strauneanu on 30/07/2019.
//  Copyright (c) 2019 Streetography. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol STPhotoCommentsRoutingLogic {
    
}

class STPhotoCommentsRouter: NSObject, STPhotoCommentsRoutingLogic {
    weak var viewController: UIViewController?
}
