//
//  STPhotoDetailsModels.swift
//  STPhotoDetails
//
//  Created by Dimitri Strauneanu on 24/06/2019.
//  Copyright (c) 2019 Streetography. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import STPhotoCore

enum STPhotoDetails {
    struct Item {
        var type: ItemType
        var model: Any?
    }
    
    enum ItemType {
        case photoImage
        case photoDetails
        
        case photoCollection
        case photoLocation
        
        case blockEntity
        case neighborhoodEntity
        case cityEntity
        case countyEntity
        case stateEntity
        case countryEntity
        
        case space
    }
    
    class DisplayedPhotoImage {
        var image: UIImage?
        var imageDominantColor: UIColor?
        var isLoadingImage: Bool = false
        weak var cellInterface: STPhotoDetailsImageCellInterface?
    }
    
    class DisplayedPhotoDetails {
        var username: String = ""
        var userImage: UIImage?
        var isLoadingUserImage: Bool = false
        var photoTime: String = ""
        var photoDescription: String = ""
        weak var cellInterface: STPhotoDetailsInfoCellInterface?
    }
    
    class DisplayedPhotoCollection {
        var title: String = ""
        var name: String = ""
        var image: UIImage?
        var isLoading: Bool = false
        weak var cellInterface: STPhotoDetailsEntityCellInterface?
    }
    
    class DisplayedPhotoEntity {
        var title: String = ""
        var name: String = ""
        var image: UIImage?
        var isLoading: Bool = false
        weak var cellInterface: STPhotoDetailsEntityCellInterface?
    }
    
    class DisplayedSpace {
        var height: CGFloat = 0
    }
    
    struct PresentPhoto {
        struct Response {
            let photo: STPhoto
        }
        
        struct ViewModel {
            let items: [STPhotoDetails.Item]
        }
    }
    
    struct PresentPhotoImage {
        struct Response {
            let image: UIImage?
        }
        
        struct ViewModel {
            let image: UIImage?
        }
    }
    
    struct PresentPhotoUserImage {
        struct Response {
            let image: UIImage?
        }
        
        struct ViewModel {
            let image: UIImage?
        }
    }
    
    struct PresentPhotoCollection {
        struct Response {
            let collection: STCollection
        }
        
        struct ViewModel {
            let name: String
        }
    }
    
    struct PresentPhotoLocationAddress {
        struct Response {
            let address: STAddress
        }
        
        struct ViewModel {
            let address: String
        }
    }
    
    struct PhotoLocationEntityLoadingState {
        struct Response {
            let type: ItemType
        }
        
        struct ViewModel {
            let type: ItemType
        }
    }
    
    struct PresentPhotoLocationEntity {
        struct Response {
            let type: ItemType
            let geoEntity: GeoEntity
        }
        
        struct ViewModel {
            let type: ItemType
            let name: String
        }
    }
    
    struct PresentPhotoLikes {
        struct Response {
            let count: Int
        }
        
        struct ViewModel {
            let title: String
        }
    }
    
    struct PresentPhotoComments {
        struct Response {
            let count: Int
        }
        
        struct ViewModel {
            let title: String
        }
    }
}
