//
//  STPhotoDetailsRouter.swift
//  STPhotoDetails
//
//  Created by Dimitri Strauneanu on 24/06/2019.
//  Copyright (c) 2019 Streetography. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol STPhotoDetailsRoutingLogic {
    func removeViewController()
}

class STPhotoDetailsRouter: NSObject, STPhotoDetailsRoutingLogic {
    weak var viewController: STPhotoDetailsViewController?
        
    func removeViewController() {
        if let navigationController = self.viewController?.navigationController {
            navigationController.popViewController(animated: true)
        } else {
            self.viewController?.dismiss(animated: true, completion: nil)
        }
    }
}
